apiVersion: v1
kind: Namespace
metadata:
  name: rt-gdfgdfg-prod
  labels:
    environment-id: env_4ec6bb2c-9b45-4a1a-a1b7-7e44f977e19d
    project-id: project_2e8e2c35-be04-4812-b650-01c4d4962610
    project-name: rt gdfgdfg
    environment-name: prod
    organization-id: org_1c58789b-c98c-4917-b321-116968ec4f8e
